routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------- All tests are here ------------*/
Route::get('/test' , 'TestController@test');

/*-- Beta functions --*/
Route::get('/logout' , function(){
    return ('home');
});

Route::get('/home', function(){
    return view('guest.demandes.index');
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/*------------------- Guest --------------------------*/
Route::get('/demandes' , function(){
    return view('guest.demandes.index');
})->name('guestDemandesIndex');

Route::get('/clients' , function(){
    return view('guest.clients.index');
})->name('guestClientsIndex');

Route::get('/guestGetDemandeTable ', 'GuestDemandeController@guestDemandeTable')->name('guestDemandeTable');
Route::get('/guestGetClientsTable' , 'GuestDemandeController@guestClientTable')->name('guestClientTable');
Route::get('/clients/{client}' , 'GuestDemandeController@show');
Route::get('/guest/export' , 'GuestDemandeController@downloadExcel')->name('exportGuest');


/*------------------- User ---------------------------*/
Route::resource('users', 'UserController');
Route::get('/dashboard/manage' , 'Usercontroller@index')->middleware('admin');
Route::get('/dashboard/manage/create' , 'UserController@create')->middleware('admin');

Route::get('/admin' , 'AdminController@index')->name('admin');
Route::get('/admin/getClientList' , 'AdminController@searchClient')->name('clientListAjax');
Route::get('/admin/add' , 'AdminController@add')->name('addAdmin');


/*-------------------- Groupe Admin -----------------*/
Route::group(['prefix' => 'admin' , 'middleware' => 'admin'] , function(){

    Route::get('/export' , 'DemandeController@downloadExcel')->name('export');
    /*----------------- Dashboard -----------------------*/
    Route::get('dashboard' , 'DashboardController@index')->name('dashboard');
    
    
    /*----------------- Demande -------------------------*/
    Route::resource('demandes' , 'DemandeController');
    Route::get('/old' , 'DemandeController@old');
    Route::post('/demandes/scrap' , 'DemandeController@scrap')->name('scrap');
    Route::get('/changerStatut' , 'DemandeController@changerStatus')->name('changerStatus');
    Route::get('/getDemandes' , 'DemandeController@getDemandes')->name('getDemandes');
    Route::get('/getDemandeTable' , 'DemandeController@demandeTable')->name('demandeTable');

    /*----------------- Client -------------------------*/
    Route::resource('clients' , 'ClientController');
    Route::get('/getClients' , 'ClientController@getClients')->name('dtable');
    Route::get('/getIncompleteClients' , 'ClientController@getIncompleteClients')->name('incompleteClients');
    Route::get('/getInactiveClients' , 'ClientController@getInactiveClients')->name('inactiveClients');
    Route::get('/activate' , 'ClientController@activate')->name('activate');
    Route::get('/desactive' , 'ClientController@desactivate')->name('desactivate');

    /*------------------ Incidents ---------------------*/
    Route::get('/incidents' , 'IncidentController@index')->name('incidents.index');

});



/*----------------- Ajax --------------------------*/
Route::get('ajax',function(){
    return view('test');
});
Route::get('/search','TestController@action')->name('action');
Route::get('/searchRadio' , 'TestController@actionRadio')->name('actionRadio');

app/Incident.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Incident extends Model
{
    protected $fillable = [
        'client_id',
        'client_name',
        'point_de_contact',
        'inc',
        'element',
        'ouvert',
        'statut',
        'ferme'
    ];

    public function client(){
        return $this->belongsTo('App\Client');
    }
}

app/Http/Controllers/IncidentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Incident;
use View;

class IncidentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $incidents = Incident::all();
        return View::make('incidents.index')->with('incidents' , $incidents);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/incidents/index.blade.php
@extends('layouts.master')

<link rel="stylesheet" href="{{ asset('css/demandes/indexStyle.css') }}">
{{-- <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css"> --}}
<link rel="stylesheet" type="text/css" href="{{asset('DataTables/css/jquery.dataTables.css')}}">

@section('content')
  @if(Session::has('success'))
	    <div class="alert alert-success">
	        {{ Session::get('success') }}
	        @php
	          Session::forget('success');
	        @endphp
	    </div>
  @endif
  @if(Session::has('already'))
	    <div class="alert alert-warning">
	        {{ Session::get('already') }}
	        @php
	          Session::forget('already');
	        @endphp
	    </div>
  @endif

<section id = 'indicator' class="content-header">
  <h1>
    Incidents
    <small>Liste des incidents</small>
  </h1>
  <ol class="breadcrumb">
  <li><a href="{{ route ('dashboard')}}"><i class="fa fa-database"></i>Dashboard</a></li>
    <li class="active">Incidents</li>
  </ol>
</section>

    <div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">

                  <div class="panel-heading" id= "box_header">
                    Liste des Incidents
                    <div class="box-tools pull-right">
                        <span id="success_message" class="label label-success"></span>
                    <a href="{{route('export')}}">
                      <button type="button" class="btn btn-box-tool" data-toggle="modal" data-toggle="tooltip" title="Excel">
                        <i id = "icons" class="fa fa-table"></i></button>
                    </a>
                    <a href="{{ route('demandes.create')}}">
                      <button type="button" class="btn btn-box-tool" title="Ajouter" data-toggle="tooltip">
                        <i id = "icons" class="fa fa-plus"></i></button>
                    </a>    
                      <button type="button" class="btn btn-box-tool" data-toggle="modal" data-target="#exampleModal" data-toggle="tooltip" title="Srap">
                        <i id = "icons" class="fa fa-cubes"></i></button>
                        
                     </div>
                  </div>

                    <div class="panel-body" >
                        
                        <table class="table table-hover" >
                            <thead>
                                <tr>
                                    <th>Element</th>
                                    <th>Nom Client</th>
                                    <th>INC</th>
                                    <th>Ouvert</th>
                                    <!-- <th>Livraison</th> -->
                                    <!-- <th>Statut</th> -->
                                    <th>Changer statut</th>
                                </tr>
                            </thead>
                            
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <form action="{{route('scrap')}}" method='post'>
      {{ csrf_field() }}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Paste the code source</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <textarea name='textS' style="resize: none;" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <input type="submit" class="btn" id = "box_header"  value='Scarp ☺'>
        </div>
      </div>
    </div>
  </form>
</div>


@endsection

<script src="{{ asset('js/app.js') }}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script type="text/javascript" charset="utf8" src="{{ asset('DataTables/js/jquery.dataTables.js') }}"></script>
{{-- <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script> --}}
<script src="{{asset('js/demandes/indexDemande.js')}}"></script>