routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------- All tests are here ------------*/
Route::get('/test' , 'TestController@test');

/*-- Beta functions --*/
Route::get('/logout' , function(){
    return ('home');
});

Route::get('/home', function(){
    return view('guest.demandes.index');
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/*------------------- Guest --------------------------*/
Route::get('/demandes' , function(){
    return view('guest.demandes.index');
})->name('guestDemandesIndex');

Route::get('/clients' , function(){
    return view('guest.clients.index');
})->name('guestClientsIndex');

Route::get('/guestGetDemandeTable ', 'GuestDemandeController@guestDemandeTable')->name('guestDemandeTable');
Route::get('/guestGetClientsTable' , 'GuestDemandeController@guestClientTable')->name('guestClientTable');
Route::get('/clients/{client}' , 'GuestDemandeController@show');
Route::get('/guest/export' , 'GuestDemandeController@downloadExcel')->name('exportGuest');


/*------------------- User ---------------------------*/
Route::resource('users', 'UserController');
Route::get('/dashboard/manage' , 'Usercontroller@index')->middleware('admin');
Route::get('/dashboard/manage/create' , 'UserController@create')->middleware('admin');

Route::get('/admin' , 'AdminController@index')->name('admin');
Route::get('/admin/getClientList' , 'AdminController@searchClient')->name('clientListAjax');
Route::get('/admin/add' , 'AdminController@add')->name('addAdmin');


/*-------------------- Groupe Admin -----------------*/
Route::group(['prefix' => 'admin' , 'middleware' => 'admin'] , function(){

    Route::get('/export' , 'DemandeController@downloadExcel')->name('export');
    /*----------------- Dashboard -----------------------*/
    Route::get('dashboard' , 'DashboardController@index')->name('dashboard');
    
    
    /*----------------- Demande -------------------------*/
    Route::resource('demandes' , 'DemandeController');
    Route::get('/old' , 'DemandeController@old');
    Route::post('/demandes/scrap' , 'DemandeController@scrap')->name('scrap');
    Route::get('/changerStatut' , 'DemandeController@changerStatus')->name('changerStatus');
    Route::get('/getDemandes' , 'DemandeController@getDemandes')->name('getDemandes');
    Route::get('/getDemandeTable' , 'DemandeController@demandeTable')->name('demandeTable');

    /*----------------- Client -------------------------*/
    Route::resource('clients' , 'ClientController');
    Route::get('/getClients' , 'ClientController@getClients')->name('dtable');
    Route::get('/getIncompleteClients' , 'ClientController@getIncompleteClients')->name('incompleteClients');
    Route::get('/getInactiveClients' , 'ClientController@getInactiveClients')->name('inactiveClients');
    Route::get('/activate' , 'ClientController@activate')->name('activate');
    Route::get('/desactive' , 'ClientController@desactivate')->name('desactivate');

    /*------------------ Incidents ---------------------*/
    Route::get('/incidents' , 'IncidentController@index')->name('incidents.index');

});



/*----------------- Ajax --------------------------*/
Route::get('ajax',function(){
    return view('test');
});
Route::get('/search','TestController@action')->name('action');
Route::get('/searchRadio' , 'TestController@actionRadio')->name('actionRadio');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','igg','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles(){
      return $this->belongsToMany('App\Role');
    }

    public function role(){
      return $this->belongsTo('App\Role');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Redirect;
use Session;
use Auth;
use View;
use App\Role;

class UserController extends Controller
{

    public function __construct(){
      $this->middleware('admin');
      $this->middleware('auth');
    }

    public function index(){
      $users = User::all();
      return View::make('users.index')->with('users' , $users);
    }

    public function create(){
      $user = User::all();
      $role = Role::all();
      return View::make('users.create')->with('user' , $user)->with('role' , $role);
    }

    public function store(){
      $validateFields = array(
        'name' => 'required',
        'igg' => 'required',
        'email' => 'required|email'
      );

      $this->validate(request(), $validateFields);

      $user = User::create([
          'name' => request()->name,
          'email' => request()->email,
          'igg' => request()->igg,
          'role_id' => request()->role,
          'password' => 'admin123'
      ]);


      return back()->with('success' , 'User created successfully');
    }

    public function show($id){
      $user = User::find($id);

      return View::make('users.create')->with('user' , $user);
    }

    public function edit($id){
      $validateFields = array(
        'name' => 'required',
        'igg' => 'required',
        'email' => 'required|email'
      );

      $this->validate(request(), $validateFields);

      $user = User::find($id);


      $user->name = request()->name;
      $user->email = request()->email;
      $user->igg = request()->igg;
      $user->role_id = request()->role;

      $user->save();

      Session::flash('success', 'The user updated successfully');
      return Redirect::to(route('users.create'));
    }

    public function destroy($id){
        $user = User::find($id);
        $user->delete();

        Session::flash('success', 'Successfully deleted the user!');
        return Redirect::to(route('users.create'));
    }

}

resources/views/users/create.blade.php
@extends('layouts.master')
@section('content')
<div class="panel panel-info">`
  @if(Session::has('success'))

	    <div class="alert alert-success">

	        {{ Session::get('success') }}

	        @php

	        Session::forget('success');

	        @endphp

	    </div>

	  @endif

@if(empty($user))
      <div class="panel-heading">ADD USER</div>
      <div class="panel-body">
        <form action="{{ route('users.store')}}" method="post">
          {{ csrf_field() }}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Complete name</label>


            <input name = "name" type="text" class="form-control" id="inputEmail4" placeholder="fullname" >


            @if ($errors->has('name'))
                	<span class="text-danger">{{ $errors->first('name') }}</span>
            	@endif
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">IGG</label>

            <input name = "igg" type="text" class="form-control" id="inputPassword4" placeholder="IGG number">


            @if ($errors->has('igg'))

                	<span class="text-danger">{{ $errors->first('igg') }}</span>

            @endif
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputCity">Email</label>

              <input name = "email" type="text" class="form-control" id="inputCity" placeholder="Email">



            @if ($errors->has('email'))

                	<span class="text-danger">{{ $errors->first('email') }}</span>

            	@endif
          </div>
          <div class="form-group col-md-6">
            <label for="inputState">Role</label>
            <select  name = "role" id="inputState" class="form-control">
              @foreach($role as $r)

                  <option value="{{ $r->id }}" name = "role">{{$r->role}}</option>

              @endforeach
            </select>
          </div>

          <div class="form-group col-md-12">

              <button style="float:right;" type="submit" class="btn btn-primary">ADD</button>

          </div>
        </div>
      </form>
      </div>
</div>
@else

      <div class="panel-heading">Update user
          <a href="{{route('users.create')}}"><img style="max-width: 20px;max-height: 20px;float:right;" src="{{ asset('assets/images/logos/add.png') }}" alt=""></a>
      </div>

      <div class="panel-body">
        <form action="{{ url('users') }}/{{ $user->id }}/edit" method="get">
          {{ csrf_field() }}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Complete name</label>
            <input name = "name" type="text" class="form-control" id="inputEmail4" placeholder="fullname" value="{{ $user->name }}">
            @if ($errors->has('name'))
                	<span class="text-danger">{{ $errors->first('name') }}</span>
            	@endif
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">IGG</label>

            <input name = "igg" type="text" class="form-control" id="inputPassword4" placeholder="IGG number" value="{{ $user->igg }}">

            @if ($errors->has('igg'))

                	<span class="text-danger">{{ $errors->first('igg') }}</span>

            @endif
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputCity">Email</label>

              <input name = "email" type="text" class="form-control" id="inputCity" placeholder="Email" value="{{ $user->email }}">



            @if ($errors->has('email'))

                	<span class="text-danger">{{ $errors->first('email') }}</span>

            	@endif
          </div>
          <div class="form-group col-md-6">
            <label for="inputState">Role</label>
            <select  name = "role" id="inputState" class="form-control">
              <option value="{{$user->role->id}}" selected="{{ $user->role->role }}" > {{ $user->role->role }}</option>
              @foreach($role as $r)
                  <option  value="{{ $r->id }}" name = "role">{{$r->role}}</option>
              @endforeach

            </select>
          </div>

          <div class="form-group col-md-12">


              <button style="float:right;" type="submit" class="btn btn-primary">Update</button

          </div>
        </div>
      </form>
      </div>
</div>
@endif
<div class="panel panel-info">
      <div class="panel-heading">USERS
      </div>
      <div class="panel-body">
        <table class="table table-hover">
        <thead>
          <tr>

            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">IGG</th>
            <th scope="col">Role</th>
            <th scope="col">Todo</th>
          </tr>
        </thead>

        <tbody>

        @foreach ($users_share as $us)
          <tr>
            <td>{{ $us->id }}</td>
            <td>{{ $us->name }}</td>
            <td>{{ $us->igg }}</td>
            <td>{{ $us->role->role }}</td>

            <td >
              <a href="{{ url('users') }}/{{ $us->id }}">
                <button style="float:right;" class = "btn btn-primary" name="button">Update</button>
              </a>

              <form class="" action="{{ route('users.destroy' , $us->id) }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                  <button  type = "submit" style="float:right;margin-right:10px;" class = "btn btn-danger" name="button">Delete</button>
              </form>

            </td>
          </tr>
        @endforeach
        </tbody>
        </table>
      </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.master')

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<link rel="stylesheet" href="{{ asset('css\clients\indexClient.css') }}">

@section('content')

<section id = 'indicator' class="content-header">
        <h1>
          Clients
          <small>Liste des clients</small>
        </h1>
        <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-user"></i>Clients</a></li>
        </ol>
    </section>
    
    <div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Clients</div>
    
                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>IGG</th>
                                    <th>Nom Complet</th>
                                    <th>Role</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $us)
                                    <tr>
                                        <td>{{ $us->id }}</td>
                                        <td>{{ $us->igg }}</td>
                                        <td>{{ $us->name }}</td>
                                        <td>{{ $us->role->role }}</td>
                                    </tr>
                                @endforeach    
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection