routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*------------------- All tests are here ------------*/
Route::get('/test' , 'TestController@test');

/*-- Beta functions --*/
Route::get('/logout' , function(){
    return ('home');
});

Route::get('/home', function(){
    return view('guest.demandes.index');
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/*------------------- Guest --------------------------*/
Route::get('/demandes' , function(){
    return view('guest.demandes.index');
})->name('guestDemandesIndex');

Route::get('/clients' , function(){
    return view('guest.clients.index');
})->name('guestClientsIndex');

Route::get('/guestGetDemandeTable ', 'GuestDemandeController@guestDemandeTable')->name('guestDemandeTable');
Route::get('/guestGetClientsTable' , 'GuestDemandeController@guestClientTable')->name('guestClientTable');
Route::get('/clients/{client}' , 'GuestDemandeController@show');
Route::get('/guest/export' , 'GuestDemandeController@downloadExcel')->name('exportGuest');


/*------------------- User ---------------------------*/
Route::resource('users', 'UserController');
Route::get('/dashboard/manage' , 'Usercontroller@index')->middleware('admin');
Route::get('/dashboard/manage/create' , 'UserController@create')->middleware('admin');

Route::get('/admin' , 'AdminController@index')->name('admin');
Route::get('/admin/getClientList' , 'AdminController@searchClient')->name('clientListAjax');
Route::get('/admin/add' , 'AdminController@add')->name('addAdmin');


/*-------------------- Groupe Admin -----------------*/
Route::group(['prefix' => 'admin' , 'middleware' => 'admin'] , function(){

    Route::get('/export' , 'DemandeController@downloadExcel')->name('export');
    /*----------------- Dashboard -----------------------*/
    Route::get('dashboard' , 'DashboardController@index')->name('dashboard');
    
    
    /*----------------- Demande -------------------------*/
    Route::resource('demandes' , 'DemandeController');
    Route::get('/old' , 'DemandeController@old');
    Route::post('/demandes/scrap' , 'DemandeController@scrap')->name('scrap');
    Route::get('/changerStatut' , 'DemandeController@changerStatus')->name('changerStatus');
    Route::get('/getDemandes' , 'DemandeController@getDemandes')->name('getDemandes');
    Route::get('/getDemandeTable' , 'DemandeController@demandeTable')->name('demandeTable');

    /*----------------- Client -------------------------*/
    Route::resource('clients' , 'ClientController');
    Route::get('/getClients' , 'ClientController@getClients')->name('dtable');
    Route::get('/getIncompleteClients' , 'ClientController@getIncompleteClients')->name('incompleteClients');
    Route::get('/getInactiveClients' , 'ClientController@getInactiveClients')->name('inactiveClients');
    Route::get('/activate' , 'ClientController@activate')->name('activate');
    Route::get('/desactive' , 'ClientController@desactivate')->name('desactivate');

    /*------------------ Incidents ---------------------*/
    Route::get('/incidents' , 'IncidentController@index')->name('incidents.index');

});



/*----------------- Ajax --------------------------*/
Route::get('ajax',function(){
    return view('test');
});
Route::get('/search','TestController@action')->name('action');
Route::get('/searchRadio' , 'TestController@actionRadio')->name('actionRadio');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'nom_complet', 
        'nom',
        'prenom',
        'email',
        'igg',
        'role_id',
        'lot_id',
        'lot_name'
    ];

    protected $hidden = [
        'password'
    ];

    public function demande(){
        return $this->hasMany('App\Demande');
    }

    public function applications(){
        return $this->belongsToMany('App\Application');
    }

    public function lot(){
        return $this->belongsTo('App\Lot');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;
use Redirect;
use View;
use App\Lot;

class ClientController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        return View::make('clients.index')->with('clients' , $clients);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        $lots = Lot::all();
        $lot = Lot::find($client->lot_id);
        return View::make('clients.demandeClient')->with('client' , $client)
                                                  ->with('lot' , $lot)
                                                  ->with('lots',$lots);
    }


    public function getIncompleteClients(){
        $client = Client::whereNull('igg')->orWhereNull('email');
        return datatables($client)->make(true);
    }


    public function getClients(){
        //$q = Client::select('id' , 'nom_complet' , 'email' , 'igg' , 'active');
        $q = Client::orderBy('nom_complet' , 'asc');
        return datatables($q)->make(true);
    }

    public function getInactiveClients(){
        $client = Client::where('active' , 'like' , '%inactive%');
        return datatables($client)->make(true);
    }

    public function activate(Request $req){
        if ($req->ajax()) {
            $id_client = $req->get('status');
            $client = Client::find($id_client);
            $client->active = 'active';
            $client->save();
            $output = 'le client ' . $client->nom_complet . ' est activé maintenant !';
            echo json_encode($output);
        }
    }

    public function desactivate(Request $req){
        if($req->ajax()){
            $id_client = $req->get('status');
            $client = Client::find($id_client);
            $client->active = 'inactive';
            $client->save();
            $output = 'le client ' . $client->nom_complet . ' est desactivé maintenant !'; 
            echo json_encode($output);
        }
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $req, Client $client)
    {
    
        $validateFields = array(
            'nom_complet' => 'max:100',
            'igg' => 'max:20',
            'email' => '',
            'al' => 'max:20',
            'vm' => 'max:100' 
        ); 

        $this->validate(request(), $validateFields);
        
        $new_client = Client::find($client->id);
        $new_client->nom_complet = $req->nom_complet;
        $new_client->igg = $req->igg;
        $new_client->email = $req->email;
        $new_client->al = $req->al;
        $new_client->vm = $req->vm;
        $new_client->net = $req->internet;
        $new_client->admin = $req->admin;
        //$new_client->lot_name = $req->lot;
        $new_client->badge_total = $req->badge;
        $new_client->lot_id = $req->lot;

        $new_client->save();

        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        //
    }

}

resources/views/clients/demandeClient.blade.php
@extends('layouts.master')
<script src="https://unpkg.com/ag-grid/dist/ag-grid.min.noStyle.js"></script>
<link rel="stylesheet" href="{{ asset('css/clients/clientDemandes.css') }}">
@section('content')
    
    <div class="box">
        <div id = 'box_header' class="box-header with-border">
          <h3 class="box-title">{{$client->nom_complet}} | {{ $client->lot_name }}</h3>

          <div class="box-tools pull-right">
            <button data-toggle="collapse" data-target="#collapseModifier" type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
          </div>
      </div>

      <div id = "collapseModifier" class = "collapse in box-body">
      
            @if($client->active == 'active')
                <div class="form-group col-md-12">
                        <button value = "{{$client->id}}" id = "btnDesactive" class="btn btn-lg btn-danger">Desactive !</button>
                </div>
                @else
                <div class="form-group col-md-12">
                        <button value = "{{$client->id}}" id = "btnActive" class="btn btn-lg btn-success">Activer</button>
                </div>
            @endif

            <div id="success_message" class="ajax_response alert alert-success" style ="display:none;" role = "alert"></div>
            
            <div id="desactive_message" class="ajax_response alert alert-danger" style ="display:none;" role = "alert"></div>

      <form action="{{ route('clients.edit' , $client) }}" method="get" autocomplete = "off">
            {{ csrf_field() }}
          <div class="form-row">
        @if(empty($client->igg))
            <div class="form-group has-warning col-md-3">
        @else
            <div class="form-group col-md-3">
        @endif
              <label>IGG</label>
              
                <input value = "{{$client->igg}}" name = "igg" type="text" class="form-control" id="igg" placeholder="IGG" >
             
              @if ($errors->has('igg'))
                    <span class="text-danger">{{ $errors->first('igg') }}</span>
              @endif

            </div>
        
        @if(empty($client->nom_complet))
            <div class="form-group has-warning col-md-3">
        @else
            <div class="form-group col-md-3">
        @endif
              <label>Nom complet</label>
              <input value = "{{$client->nom_complet}}" name = "nom_complet" type="text" class="form-control" id="nom_complet" placeholder="Nom complet">
              @if ($errors->has('nom_complet'))
                    <span class="text-danger">{{ $errors->first('nom_complet') }}</span>
              @endif
            </div>
          </div>
          <div class="form-row">
        @if(empty($client->email))
            <div class="form-group has-warning col-md-6">
        @else
            <div class="form-group col-md-6">
        @endif       
              <label>Email</label>
                <input value = "{{$client->email}}" name = "email" type="text" class="form-control" id="email" placeholder="Email">

              @if ($errors->has('email'))
                    <span class="text-danger">{{ $errors->first('email') }}</span>
              @endif
            </div>

            <div class="form-group col-md-3">
              <label for="inputState">Badge Total</label>

              <select class="form-control" name="badge" id="badge">
                @if($client->badge_total == 0)
                    <option value="1">Avec</option>
                    <option selected value="0">Sans</option>
                @else
                    <option selected value="1">Avec</option>
                    <option value="0">Sans</option>
                @endif
              </select>
              
              @if ($errors->has('badge'))
                    <span class="text-danger">{{ $errors->first('badge') }}</span>
              @endif  
            </div>

            <div class="form-group col-md-3">
              <label for="inputState">Admin</label>

              <select class="form-control " name="admin" id="admin">
                @if($client->admin == 0)
                    <option value="1">Avec</option>
                    <option selected value="0">Sans</option>
                @else
                    <option selected value="1">Avec</option>
                    <option value="0">Sans</option>
                @endif
              </select>
              
              @if ($errors->has('admin'))
                    <span class="text-danger">{{ $errors->first('admin') }}</span>
              @endif  
            </div>

            <div class="form-group col-md-3">
              <label for="inputState">Internet</label>

              <select class="form-control" name="internet" id="internet">
                @if($client->net == 0)
                    <option value="1">Avec</option>
                    <option selected value="0">Sans</option>
                @else
                    <option selected value="1">Avec</option>
                    <option value="0">Sans</option>
                @endif
              </select>
              
              @if ($errors->has('internet'))
                    <span class="text-danger">{{ $errors->first('internet') }}</span>
              @endif  
            </div>

            <div class="form-group col-md-3">
              <label for="inputState">Lot</label>

              <select class="form-control" name = "lot">
                @if($client->lot->nom == '' || $client->lot->nom == 'pas de lot')
                    <option selected value="11">Pas de lot</option>
                    @foreach($lots as $l)
                        <option value="{{ $l->id }}" name ="lot" >{{ $l->nom }}</option>
                    @endforeach
                @else    
                    <option selected value="{{$client->lot_id}}">{{$client->lot->nom}}</option>
                    @foreach($lots as $l)
                        <option value="{{ $l->id }}" name ="lot">{{ $l->nom }}</option>
                    @endforeach
                @endif    
              </select>
              
              @if ($errors->has('lot'))
                    <span class="text-danger">{{ $errors->first('lot') }}</span>
              @endif  
            </div>
            
        @if(empty($client->al))
            <div class="form-group has-warning col-md-3">
        @else
            <div class="form-group col-md-3">
        @endif 
              <label>Compte AL</label>
              <input value = "{{$client->al}}" name = "al" type="text" class="form-control" id="al" placeholder="Compte AL">
              @if ($errors->has('al'))
                    <span class="text-danger">{{ $errors->first('al') }}</span>
              @endif
            </div>
        
        @if(empty($client->vm))
            <div class="form-group has-warning col-md-3">
        @else
            <div class="form-group col-md-3">
        @endif 

              <label>Nom VM</label>
              <input value = "{{$client->vm}}" name = "vm" type="text" class="form-control" id="vm" placeholder="Nom VM">
              @if ($errors->has('vm'))
                    <span class="text-danger">{{ $errors->first('vm') }}</span>
              @endif
            </div>
            
            <div class="form-group col-md-12">
                <button id ="btn" type="submit" class="btn btn-primary">Modifier</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    
    <div class="box">
            <div id = 'box_header' class="box-header with-border">
                <h3 class="box-title">Les dernières demandes</h3>

                <div class="box-tools pull-right">
                    <button data-toggle="collapse" data-target="#collapseDemande" type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-plus"></i></button>
                </div>
            </div>

            <div id = "collapseDemande" class="collapse box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">RITM</th>
                        <th scope="col">Element</th>
                        <th scope="col">Statut</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($client->demande as $d)
                        <tr>
                            <td>{{ $d->ritm}}</td>
                            <td>{{ $d->element}}</td>
                            <td>{{ $d->statut}}</td>
                        </tr>
                    @endforeach      
                    </tbody>
                </table>    
            </div>
    </div>

        <div class="box ">
            <div id = 'box_header' class="box-header with-border">
                <h3 class="box-title">Liste des applications (par lot)</h3>

                <div class="box-tools pull-right">
                    <button data-toggle = "collapse" data-target = "#collapseApplication" type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-plus"></i></button>
                </div>
            </div>

            <div id = "collapseApplication" class="collapse box-body">
                <table class="table table-hover">
                    <thead>
                        @if(isset($lot))
                            @foreach($lot->applications_lot as $app)
                                <th>{{ $app->nom }}</th>
                            @endforeach
                           
                    </thead>
                    <tbody>
                            @foreach($lot->applications_lot as $app)
                                <td id = "na">N/A</td>
                            @endforeach
                    </tbody>
                        @endif 
                </table>    
            </div>
        </div>

        <div class="box ">
            <div id = 'box_header' class="box-header with-border">
                <h3 class="box-title">Liste des applications</h3>

                <div class="box-tools pull-right">
                    <button data-toggle = "collapse" data-target = "#collapseApplication2" type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-plus"></i></button>
                </div>
            </div>

            <div id = "collapseApplication2" class="collapse box-body">
                <table class="table table-hover">
                    <tbody>
                            @foreach($client->applications as $app)
                            <tr>
                                <td> - {{ $app->nom }}</td>
                            </tr>
                            @endforeach
                           
                    </tbody>
                </table>    
            </div>
        </div> 


    <div class="box ">
            <div id = 'box_header' class="box-header with-border">
                <h3 class="box-title">Accès transverses</h3>

                <div class="box-tools pull-right">
                    <button data-toggle ="collapse" data-target = "#collapseAcces" type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-plus"></i></button>
                </div>
            </div>

            <div id = "collapseAcces" class="collapse box-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Badge total</th>
                        <th scope="col">IET</th>
                        <th scope="col">Droits admin</th>
                        <th scope="col">AL#</th>
                        <th scope="col">Net</th>
                        <th scope="col">VM#</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr >
                            @if($client->badge_total == 0)<td id = "na">N/A</td>@else<td id = "ok">OK</td>@endif
                            @if($client->iet == 0)<td id = "na">N/A</td>@else<td id = "ok">OK</td>@endif
                            @if($client->admin == 0)<td id = "na">N/A</td>@else<td id = "ok">OK</td>@endif
                            @if($client->al == "")<td id = "na">N/A</td>@else<td id = "ok">{{$client->al}}</td>@endif
                            @if($client->net == 0)<td id = "na">N/A</td>@else<td id = "ok">OK</td>@endif
                            @if($client->vm == "")<td id = "na">N/A</td>@else<td id = "ok">{{$client->vm}}</td>@endif
                        </tr>
                    </tbody>
                </table>    
            </div>
    </div>


@endsection

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script type="text/javascript" src="{{asset('js/clients/demandeclient.js')}}"></script>

resources/views/clients/index.blade.php
@extends('layouts.master')

@section('content')

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
<link rel="stylesheet" href="{{ asset('css\clients\indexClient.css') }}">

<section id = 'indicator' class="content-header">
    <h1>
      Clients
      <small>Liste des clients</small>
    </h1>
    <ol class="breadcrumb">
    <li><a href="{{ route ('dashboard')}}"><i class="fa fa-user"></i>Dashboard</a></li>
      <li class="active">Client</li>
    </ol>
</section>

<div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Clients</div>

                <div class="panel-body">
                    <table class="table table-hover" id="clientsTable">
                        <thead>
                            <tr>
                                <th>Active</th>
                                <th>IGG</th>
                                <th>Nom Complet</th>
                                <th>Email</th>
                                <th>Lot</th>
                                <th>Edition</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
<script src="{{ asset('js/app.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script src="{{ asset('js/clients/indexClient.js') }}"></script>